// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: proto/mcppb/mcp_messages.proto

package mcppb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TryCleanupIfUninitialized struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TryCleanupIfUninitialized) Reset() {
	*x = TryCleanupIfUninitialized{}
	mi := &file_proto_mcppb_mcp_messages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TryCleanupIfUninitialized) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TryCleanupIfUninitialized) ProtoMessage() {}

func (x *TryCleanupIfUninitialized) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mcppb_mcp_messages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TryCleanupIfUninitialized.ProtoReflect.Descriptor instead.
func (*TryCleanupIfUninitialized) Descriptor() ([]byte, []int) {
	return file_proto_mcppb_mcp_messages_proto_rawDescGZIP(), []int{0}
}

type CheckSessionTTL struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckSessionTTL) Reset() {
	*x = CheckSessionTTL{}
	mi := &file_proto_mcppb_mcp_messages_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckSessionTTL) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckSessionTTL) ProtoMessage() {}

func (x *CheckSessionTTL) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mcppb_mcp_messages_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckSessionTTL.ProtoReflect.Descriptor instead.
func (*CheckSessionTTL) Descriptor() ([]byte, []int) {
	return file_proto_mcppb_mcp_messages_proto_rawDescGZIP(), []int{1}
}

type RegisterConnection struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConnectionId  string                 `protobuf:"bytes,1,opt,name=connectionId,proto3" json:"connectionId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterConnection) Reset() {
	*x = RegisterConnection{}
	mi := &file_proto_mcppb_mcp_messages_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterConnection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterConnection) ProtoMessage() {}

func (x *RegisterConnection) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mcppb_mcp_messages_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterConnection.ProtoReflect.Descriptor instead.
func (*RegisterConnection) Descriptor() ([]byte, []int) {
	return file_proto_mcppb_mcp_messages_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterConnection) GetConnectionId() string {
	if x != nil {
		return x.ConnectionId
	}
	return ""
}

type RegisterConnectionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterConnectionResponse) Reset() {
	*x = RegisterConnectionResponse{}
	mi := &file_proto_mcppb_mcp_messages_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterConnectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterConnectionResponse) ProtoMessage() {}

func (x *RegisterConnectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mcppb_mcp_messages_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterConnectionResponse.ProtoReflect.Descriptor instead.
func (*RegisterConnectionResponse) Descriptor() ([]byte, []int) {
	return file_proto_mcppb_mcp_messages_proto_rawDescGZIP(), []int{3}
}

func (x *RegisterConnectionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegisterConnectionResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type StringMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StringMsg) Reset() {
	*x = StringMsg{}
	mi := &file_proto_mcppb_mcp_messages_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StringMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringMsg) ProtoMessage() {}

func (x *StringMsg) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mcppb_mcp_messages_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringMsg.ProtoReflect.Descriptor instead.
func (*StringMsg) Descriptor() ([]byte, []int) {
	return file_proto_mcppb_mcp_messages_proto_rawDescGZIP(), []int{4}
}

func (x *StringMsg) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_mcppb_mcp_messages_proto protoreflect.FileDescriptor

const file_proto_mcppb_mcp_messages_proto_rawDesc = "" +
	"\n" +
	"\x1eproto/mcppb/mcp_messages.proto\x12\x05mcppb\"\x1b\n" +
	"\x19TryCleanupIfUninitialized\"\x11\n" +
	"\x0fCheckSessionTTL\"8\n" +
	"\x12RegisterConnection\x12\"\n" +
	"\fconnectionId\x18\x01 \x01(\tR\fconnectionId\"L\n" +
	"\x1aRegisterConnectionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"%\n" +
	"\tStringMsg\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessageB4Z2github.com/traego/scaled-mcp/pkg/proto/mcppb;mcppbb\x06proto3"

var (
	file_proto_mcppb_mcp_messages_proto_rawDescOnce sync.Once
	file_proto_mcppb_mcp_messages_proto_rawDescData []byte
)

func file_proto_mcppb_mcp_messages_proto_rawDescGZIP() []byte {
	file_proto_mcppb_mcp_messages_proto_rawDescOnce.Do(func() {
		file_proto_mcppb_mcp_messages_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_mcppb_mcp_messages_proto_rawDesc), len(file_proto_mcppb_mcp_messages_proto_rawDesc)))
	})
	return file_proto_mcppb_mcp_messages_proto_rawDescData
}

var file_proto_mcppb_mcp_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_mcppb_mcp_messages_proto_goTypes = []any{
	(*TryCleanupIfUninitialized)(nil),  // 0: mcppb.TryCleanupIfUninitialized
	(*CheckSessionTTL)(nil),            // 1: mcppb.CheckSessionTTL
	(*RegisterConnection)(nil),         // 2: mcppb.RegisterConnection
	(*RegisterConnectionResponse)(nil), // 3: mcppb.RegisterConnectionResponse
	(*StringMsg)(nil),                  // 4: mcppb.StringMsg
}
var file_proto_mcppb_mcp_messages_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_mcppb_mcp_messages_proto_init() }
func file_proto_mcppb_mcp_messages_proto_init() {
	if File_proto_mcppb_mcp_messages_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_mcppb_mcp_messages_proto_rawDesc), len(file_proto_mcppb_mcp_messages_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_mcppb_mcp_messages_proto_goTypes,
		DependencyIndexes: file_proto_mcppb_mcp_messages_proto_depIdxs,
		MessageInfos:      file_proto_mcppb_mcp_messages_proto_msgTypes,
	}.Build()
	File_proto_mcppb_mcp_messages_proto = out.File
	file_proto_mcppb_mcp_messages_proto_goTypes = nil
	file_proto_mcppb_mcp_messages_proto_depIdxs = nil
}
